[package]
name = "globignore"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "string"] }
gitignore = { path = "../gitignore/" }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml_ng = "0.10.0"
